### ISSUE TITLE
How to run Blastall before MCL?

### ISSUE THREAD

**Issue by br302005** [JohannesBuchner/mcl#2]
Hello,

I am trying to use MCL to do paralog clustering of 13 genomes for comparative genomics. I have been using the protocol "Using MCL to Extract Clusters from Networks" as a reference for doing this. In the protocol, it says that I have to run `blastall -p blastp` with the `-m8` parameter on my protein fasta files before I can run MCL. It states that there are instructions on how to do this in the supplementary material, but I have not been able to find them. I am confused on how to do this step as it is has not worked for me so far. How do I do this so I can move on to running MCL? Thank you in advance.

-Brittany

**Comment by JohannesBuchner** [comment]
please ask upstream, this is just a copy.
